# Generated by Django 6.0 on 2026-01-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookReview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzija',
            name='datum',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
