# Generated by Django 6.0 on 2026-01-31 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookReview', '0002_alter_recenzija_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzija',
            name='datum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
